version: '3'

services:
  web:
    image: node:8.11.3
    network_mode: host
    command: npm run watch
    working_dir: /usr/src/app
    volumes:
      - ./:/usr/src/app
    ports:
      - 3000:3000
    depends_on:
      - db
    environment:
      DB_CONN_DATABASE: team-up
      DB_CONN_HOST: db
      DB_CONN_PASSWORD: password
      DB_CONN_PORT: 5432
      DB_CONN_USER: postgres
      NODE_ENV: development
  db:
    image: postgres:10.4
    ports:
      - 5432:5432
    volumes:
      - ./db/local_database_volume:/var/lib/postgresql/data
    environment:
      PGDATA: /run/pgsql-10.4-data
      POSTGRES_DB: team-up
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
